- .env.sample
- README.md
- config/knexfile.js
Heroku has SSL settings that required some config changes. I made those changes last night in main but needed to make other updates for dev and testing envs to ensure it works in all environments.
> fixes knex config for both local and heroku pg connections

- __tests__/routes/profiles.test.js
- api/profile/profileModel.js
- api/profile/profileRouter.js
- api/utils/db-helper.js
I created a generic DB helper for basic crud operations to reduce boilerplate as we add additional tables+routes. Profiles routes + tests have been updated to use it.
> added generic db-helper method and updated profiles routes to use it

- __tests__/routes/profiles.test.js
- api/API-README.MD
- api/app.js
- api/middleware/authorization.js
- api/profile/profileModel.js
- api/profile/profileRouter.js
- data/migrations/20200625220949_create-profile.js
- data/seeds/001_profiles.js
- package-lock.json
Lots of changes:
- Adding Roles to the user table 
- Updating seed data
- requiring Auth across entire app except for root
- Adds default avatar img urls when none are submitted on create
- Protects profile edit route to admins or limited actions for profile owner
- Creates stubbed admin routes for create and delete users
- Adds API reference README
> Feature/ User Roles & Auth

- .env.sample
- api/API-README.MD
- api/middleware/authRequired.js
- api/profile/profileModel.js
- api/profile/profileRouter.js
- api/utils/splitNameField.js
- config/okta.js
- data/migrations/20200625220949_create-profile.js
- data/seeds/001_profiles.js
- package-lock.json
- package.json
This pull integrates into the Okta API in order to write name data to Okta to the data between our DB and Okta in sync. Necessary changes to support this feature:
- Splits our name field to First and Last name columns
- Updates the authRequired middleware to support first and last name
To run this locally you'll need to npm i and get the Okta env variables from me.
> Feature/Integrate First and Last Names with Okta

- api/program/programModel.js
- api/program/programRouter.js
This PR adds user info to the programs routes so admins and program managers can see who is associated with a given program.
> updates programs routes to return associated users

- api/profile/profileModel.js
- data/seeds/001_profiles.js
- data/seeds/003_programs_users.js
- data/seeds/006_service_entries.js
- data/seeds/007_services_providers.js
This PR updates seed data for profiles to match Okta profile ids and reinstates the Okta name syncing in the profiles model.
> Bug/Okta Syncing

- package-lock.json
- package.json
Description:
- Adds the "migrate", "rollback", "seed" scripts into package.json
- These scripts allow developers to write repetitive commands faster and with less chance of misspelling 
- Similar Heroku commands for production database coming soon
- Old commands will still work, and we can add new scripts as needed
Changes:
_Template : "current command" = "new command"_
- "npm run knex migrate:latest" = "npm run migrate"
- "npm run knex migrate:rollback" = "npm run rollback"
- "npm run knex seed:run" = "npm run seed"
Type of Change:
- Syntactic sugar/Creature comfort
- Has been tested locally with Postgres 👍
- No new warnings or conflicts
> Adds local DB scripts for migrate, rollback, and seeding

- __tests__/routes/recipient.test.js
- api/recipient/recipientRouter.js
- Filled out GET and DELETE requests in recipientRouter.js file.
- Created a test for recipients folder.
- Working on testing through jest in backend testing GET endpoints and DELETE endpoint.
> Filled out GET and DELETE requests in recipientRouter.js file.

- .eslintrc.js
- api/recipient/recipientRouter.js
- package-lock.json
- package.json
- Fixed the prettier 'CR' error
- Filled out PUT and POST endpoint in recipientRouter.js
Type of change:
- Needed functionality for adding and updating Family Promise recipients.
New feature (non-breaking change which adds functionality)
Has this feature been tested before the conflict?
Yes, POST functionality needs to be reviewed. Currently getting the below error:
{
"error": "insert into \"recipients\" (\"address\", \"age\", \"city\", \"ethnicity\", \"household_size\", \"name\", \"state\", \"veteran_status\", \"zip_code\") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning * - duplicate key value violates unique constraint \"recipients_pkey\""
}
Has this feature been tested after conflict?
*change Status*
> Filled out PUT and POST endpoint in recipientRouter.js

- data/migrations/006-recipients.js
- data/seeds/006_recipients.js
- Pair programmed with Tara and Jennifer via Zoom
- Went over current form values in addRecipientForm.js in the front-end to match up key pairs.
- Updated previous "ethnicity" column with "race"
- Included inclusive "gender" column
- Locally tested
> Updated recipients table value, and added gender column

- api/API-README.MD
Description
**Invited Collaborator(s) to Review
- Tara Timmerman
- Nathan Hietala
- I went ahead and updated the API-README.md file located within the /api folder to include the recipients endpoints and descriptions of each path, including displays of what the data looks like for GET, PUT, or DELETE requests.
- I also reorganized how the display was reading for better readability on endpoints other than recipients, such as moving lines of descriptions down a line to make the display cleaner to read like line 5 became lines 5 and 6.
- Added small capitalizations and grammar to some words such as status => Status on line 149.
Describe in detail what's been modified/created
- This work was done for informational and documentation purposes within …
> Updated API-README file to include recipient endpoints.

- api/app.js
- api/household/householdRouter.js
- Added Nathan as a reviewer
- Created CRUD endpoints for new household db table
- Configured household routing in app.js
- Tested CRUD functionality locally on Postman
> Created household endpoints and configured app.js

- api/API-README.MD
Description
**Invited Collaborator(s) to Review
Jennifer Kramer
Updated API-README.MD to include:
- New Recipient requirements
- New Household endpoints and requirements
This update was necessary as the API-README file contains information for the user about the endpoints and their requirements. and should stay up-to-date with any changes.
> Updated API-README

- api/serviceEntries/serviceEntriesModel.js
- api/serviceEntries/serviceEntriesRouter.js
Invited Jennifer and Nathan to Review
- Created a new serviceEntriesModel.js file that allowed a single GET request to obtain all information for service_entires, recipients, service_types, statuses for the Service Form.
- Imported the .findAll helper function from serviceEntriesModel.js file into serviceEntriesRouter.js and utilized in the first GET request.
Front End needed data from multiple tables in one GET request.
New feature (non-breaking change which adds functionality)
Tested locally and confirmed functionality using Postman.
Here is an example of a singular service entry response object:
```
{
"id": 15,
"service_type_id": 1,
"provided_at": "2021-02-02T05:49:51.029Z",
"notes": "Nulla sapiente ea asperiores voluptas qui aut aperiam …
```
> Created a new serviceEntriesModel and connected to serviceEntriesRoute

- api/API-README.MD
Description
**Invited Collaborator(s) to Review
- Tara Timmerman
- Nathan Hietala
- On the preview of Github for this API-README.MD file, I noticed that the rows for the representative tables were not lining up correctly, so I went ahead and corrected those rows so the information doesn't fall onto an empty row.
Describe in detail what's been modified/created
- This was done for better clarity of how the information of the data is presented.
Type of change
- Correction
Completed, ready to review, and merge
Checklist
My code follows the style guidelines of this project
I have performed a self-review of my own code
My code has been reviewed by at least one peer
I have made corresponding changes to the documentation
My changes generate no new …
> Fixed representative data tables in API-README file, removing unnecessary rows.

- data/newMigrations/004-locations.js
- data/newMigrations/009-households.js
Description
• created new migration files for Households and Locations tables.
• In order to restructure the database to fit our desired schema
Type of change
Change Status
Checklist
> New feature/add new migration tables/brian c

- data/newMigrations/011-phone_numbers.js
created new migration file for phone numbers table
In order to restructure the database to fit our desired schema
> new phone numbers table

- data/newMigrations/006-service_types.js
- data/newMigrations/008-service_type_categories.js
Description
• created new migration files
• In order to restructure the database to fit our desired schema
Type of change
• Breaking feature? We will have to rewrite some of the model files
Change Status
Checklist
> service_types and service_type_categories migration fix

- data/newMigrations/005-program_providers.js
- data/newMigrations/007-service_type_providers.js
Description
• created new migration files for program-providers table and service-type-providers table
• In order to restructure the database to fit our desired schema
Type of change
Change Status
Checklist
> created migration files

- data/newMigrations/001-programs.js
- data/newMigrations/003-service_categories.js
Description
• Created programs table in newMigrations folder
• We're redoing all tables to add some tables and restructure others.
Type of change
Change Status
Checklist
> mew programs table in newMigrations folder

- data/newMigrations/002-providers.js
- data/newMigrations/017-service_entries.js
Description
New migrations for the new DB schema
• created new migration files for providers table and service entries table
• In order to restructure the database to fit our desired schema
Type of change
Change Status
Checklist
> Creates new migrations for providers and service entries

- api/metrics/metricsModel.js
Description  
• changed model function in the metricsModel.js file to work correctly with new column names in the updated database schema
• to ensure that the frontend can properly communicate with the database
• New feature (non-breaking change which adds functionality)  
Checklist  
> updated metricsModel to function with new database schema

- api/middleware/models.js
Description  
• changed model function in the middleware/model.js file to work correctly with new column names in the updated database schema  
• to ensure that the frontend can properly communicate with the database  
• New feature (non-breaking change which adds functionality)  
Checklist  
> rewrote middleware models.js file to function properly with new database schema

- api/serviceTypes/serviceTypeModel.js
- data/migrations/001-programs.js
- data/migrations/003-service_categories.js
- data/migrations/010-genders.js
- data/migrations/011-races.js
- data/migrations/012-ethnicities.js
- data/migrations/013-recipients.js
Description  
• changed model function in the serviceTypeModel.js file to work correctly with new column names in the updated database schema  
• to ensure that the frontend can properly communicate with the database  
• New feature (non-breaking change which adds functionality)  
Checklist  
> updated serviceTypeModel.js to fit new migration schema

- api/program/programModel.js
- api/serviceEntries/serviceEntriesModel.js
- package.json
Reverts Lambda-School-Labs/family-promise-service-tracker-be-a#69
> Revert "updated programModel.js and serviceEntriesModel.js"

- api/program/programModel.js
Description
• changed model function in the programModel.js file to work correctly with new column names in the updated database schema
• to ensure that the frontend can properly communicate with the database
Type of change
Change Status
Checklist
> updated programModel.js

- api/serviceEntries/serviceEntriesModel.js
Description  
• changed model function in the serviceEntriesModel.js file to work correctly with new column names in the updated database schema  
• to ensure that the frontend can properly communicate with the database  
• New feature (non-breaking change which adds functionality)  
Checklist  
> updated serviceEntriesModel to work with new database schema

- api/app.js
- api/middleware/authRequired.js
- api/provider/providerModel.js
- api/provider/providerRouter.js
Description  
• updated old profile folder/model/router to reflect database table name change to provider.  authrequested.js model also updated and app.js updated as well.
• to ensure that the frontend and okta can properly communicate with the database  
• updated
Checklist  
> updated variables and connections for old profile model/router

- api/recipient/recipientModel.js
- api/recipient/recipientRouter.js
Description  
• added routerModel.js file and added findRecipientByName endpoint
• to ensure that the frontend can find previously added recipient by name
• updated  
Checklist  
> created recipientModel, added findRecipientByName endpoint

- api/middleware/authRequired.js
Description  
• updated variable names in authRequired.js
• to ensure that the frontend and okta can properly communicate with the database  
• updated  
Checklist  
> updated variable names in authRequired.js

- __tests__/middleware/canCrudServiceType.test.js
- __tests__/middleware/requireAdmin.test.js
- api/API-README.MD
- api/middleware/authorization.js
Fixes capitalization mismatch in roles due to the updated schema
> Bug fix/fixing capitalization spelling mismatch

- api/household/householdModel.js
- api/household/householdRouter.js
Summary of your changes
- made create function for households
- made findById function for households
-created the 'create' and 'findById' functions in the householdModel file
Why?
-in order to give the user the ability to create a new household in the database
- New feature (non-breaking change which adds functionality)
- Completed, ready to review and merge
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts
> made Create and FindById functions in householdModel file

- api/recipient/recipientModel.js
- api/recipient/recipientRouter.js
Reverts Lambda-School-Labs/family-promise-service-tracker-be-a#95
> Revert "Refactor/clean up recipient model" - Revert this 1st

- __tests__/routes/veteran.test.js
- api/recipient/recipientModel.js
- api/recipient/recipientRouter.js
- api/veteran/veteranModel.js
- api/veteran/veteranRouter.js
Reverts Lambda-School-Labs/family-promise-service-tracker-be-a#94
> Revert "Refactor/moving veteran endpoint to recipients"- Revert this 2nd

- api/API-README-SERVICE-ENTRIES.md
- data/seeds/016-service_entries.js
Update service_entry_data format and docs
Update service_entry_data format and docs. 
Data now in object instead of array of objects
Will make it easier for frontend to store and read data
- New feature (non-breaking change which adds functionality)
> Feature/refine seeds/service entries

- api/recipient/recipientModel.js
fixedRecipient model.  was preventing add recipient endpoint from working
Summary of your changes
Why?
- New feature (non-breaking change which adds functionality)?
- Bug Fix?
- In progress?
- etc.
> fixedRecipient model

- data/migrations/013-recipients.js
Commented out notNullable since the add recipient TRX is not complete
Why?
- Bug Fix
- Completed, ready to review and merge
> commented out notNullable, add recipient trx not complete

- docs/API-README.MD
Fixes Links in API-README.md
Fixes Links in API-README.md to the API-README-SERVICE-ENTRIES.md file
Link Didn't Work
- Bug Fix
- Completed, ready to review and merge
> Bug fix/link fix

- api/program/programRouter.js
- api/utils/db-helper.js
Summary of your changes
Delete function on Programs is now functional.
A new db-helper was created
Created a new db-helper specifically for removing programs_id
for crud operations to be functional
- CRUD operation fixed
- In progress?
> Programs Delete function fixed BE

- api/provider/providerModel.js
- api/provider/providerRouter.js
- config/knexfile.js
- docker-compose.yml
- package-lock.json
- package.json
Set up POST provider API endpoint
Got rid of the stub 
To give the administrators the ability to add future providers/employees
New feature 
In progress
> Adding POST provider functionality

- README.md
Clarified instructions for getting backend running when api-dev database does not exist on postgres admin on localhost.
Getting backend running following instructions of current readme, investigating issues with our repo / docker  on windows, discussing with engineering lead for labs as well as previous backend engineer for FP-Backend, editing readme doc
To ensure that the instructions are more clear for future labs cohorts working on this
Why?
So they can get started quicker & with less frustration, and move onto more pressing issues
- Readme instructions clarification / bug handling 
- Ready to review & merge
> updated readme instructions for launching docker/postgres for windows

- data/migrations/013-recipients.js
- data/seeds/013-recipients.js
Changed the qualify_status column to active column due to naming convention.
Changed the qualify_status column to active column
Why?
- New feature (non-breaking change which adds functionality)?
- Bug Fix?
- In progress?
- etc.
> Changed the qualify_status column to active_status

- api/middleware/authRequired.js
- api/middleware/authorization.js
- api/middleware/models.js
- api/serviceEntries/serviceEntriesModel.js
- api/serviceEntries/serviceEntriesRouter.js
- api/serviceTypes/serviceTypeModel.js
- data/migrations/005-program_providers.js
- data/migrations/016-service_entries.js
- package-lock.json
Summary of your changes
- fixed several variable names to match new database
- nneded to match up with new tables and Schemas
- Bug Fix
- [ -] Endpoint tested with Postman, or Unit test.
- [- ] My code follows the style guidelines of this project
- [- ] I have performed a self-review of my own code
- [- ] My changes generate no new warnings
- [- ] There are no merge conflicts
> Feature/new service entry log/m habermas

- api/locationTypes/locationTypesModel.js
- api/locationTypes/locationTypesRouter.js
- api/serviceTypePrograms/serviceTypeProgramsModel.js
- api/serviceTypePrograms/serviceTypeProgramsRouter.js
location types and STP endpoints set up
made basic CRUD foundations for the new team to work off of
see above
- New feature (non-breaking change which adds functionality)?
- In progress?
- etc.
> location types and STP endpoints set up

- api/app.js
- api/emailAddresses/emailAddressRouter.js
- api/phoneNumbers/phoneNumberRouter.js
- api/providerRoles/providerRoleRouter.js
- api/races/raceRouter.js
- api/serviceRatings/serviceRatingRouter.js
naming Bug
Why?
- New feature (non-breaking change which adds functionality)?
- Bug Fix?
- In progress?
- etc.
> updated final endpoints

- api/app.js
- api/dsService/dsRouter.js
- api/emailAddresses/emailAddressRouter.js
- api/ethnicities/ethnicityRouter.js
- api/genders/genderRouter.js
- api/household/householdModel.js
- api/household/householdRouter.js
- api/index/indexRouter.js
- api/location/locationRouter.js
- api/locationTypes/locationTypesRouter.js
- api/phoneNumbers/phoneNumberRouter.js
- api/program/programRouter.js
- api/provider/providerModel.js
- api/provider/providerRouter.js
- api/providerRoles/providerRoleRouter.js
- api/races/raceRouter.js
- api/recipient/recipientRouter.js
- api/serviceEntries/serviceEntriesRouter.js
- api/serviceRatings/serviceRatingRouter.js
- api/serviceTypePrograms/serviceTypeProgramsRouter.js
- api/serviceTypes/serviceTypeRouter.js
- api/serviceUnits/serviceUnitRouter.js
- api/statuses/statusesRouter.js
- config/jsdoc.js
My goal was to document our project's API with [Swagger](https://swagger.io/.) 
Loom link: https://www.loom.com/share/a94ac3d62a9d4c87a1e39f6278d1b790
Using the endpoint /api-docs, users will be able to test every endpoint of our API and standardize the different requests and responses. 
All endpoints, with the exception of the index, require Okta authentication. 
For Chrome:
1. Log in to [Family Promise Service Tracker](https://a.familypromiseservicetracker.dev/login)
2. Inspect the page in Developer Mode (ctrl + shift + i)
3. Select the Application tab
4. Select okta-token-storage
5. Drop down idtoken and copy the value
6. Enter the idtoken on the /api-docs to access all authenticated routes
I documented all the endpoints and HTTP requests for our API.
This work was done to standardized …
> API documentation update
